# This workflow ensures that the plugin can build on Minecraft's latest version using Java 17 (as of Minecraft 1.19)

name: Java 17 - Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, release/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B package --file pom.xml
